apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-system
  labels:
    app: memory-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: memory-system
  template:
    metadata:
      labels:
        app: memory-system
    spec:
      containers:
      - name: memory-system
        image: ai-memory-system:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: MONGO_HOST
          value: "mongodb-service"
        - name: MONGO_PORT
          value: "27017"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        - name: RAY_ADDRESS
          value: "ray://ray-service:10001"
        - name: API_HOST
          value: "0.0.0.0"
        - name: API_PORT
          value: "8000"
        - name: MODEL_ID
          valueFrom:
            configMapKeyRef:
              name: memory-system-config
              key: model_id
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: memory-system-service
spec:
  selector:
    app: memory-system
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: memory-system-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: memory-system.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: memory-system-service
            port:
              number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: memory-system-config
data:
  model_id: "gpt2"
  environment: "production" 
